// onboarding

export const READ_EXTERNAL_STORAGE_PERMISSION_GRANTED: string = "READ_EXTERNAL_STORAGE_PERMISSION_GRANTED";
export const READ_EXTERNAL_STORAGE_PERMISSION_DENIED: string = "READ_EXTERNAL_STORAGE_PERMISSION_DENIED";
export const READ_EXTERNAL_STORAGE_PERMISSION_BLOCKED: string = "READ_EXTERNAL_STORAGE_PERMISSION_BLOCKED";
export const ONBOARDING_COMPLETE: string = "ONBOARDING_COMPLETE";

// music

export const FETCHED_SONGS: string = "FETCHED_SONGS";
export const SET_CURRENT_SONG: string = "SET_CURRENT_SONG";
export const RESET_CURRENT_SONG: string = "RESET_CURRENT_SONG";
export const IS_PLAYING: string = "IS_PLAYING";
export const IS_NOT_PLAYING: string = "IS_NOT_PLAYING";

// player modal

export const SHOW_PLAYER_MODAL: string = "SHOW_PLAYER_MODAL";
export const HIDE_PLAYER_MODAL: string = "HIDE_PLAYER_MODAL";